status-response: "ok"
adapters:
  rubicon:
    enabled: true
    XAPI.Username: user1
    XAPI.Password: password1
  improvedigital:
    enabled: true
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  filesystem:
    settings-filename: sample/sample-app-settings.yaml
    stored-requests-dir:
    stored-imps-dir:
    stored-responses-dir:
gdpr:
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
