status-response: "ok"
adapters:
  alkimi:
    enabled: true
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: false
  generate-storedrequest-bidrequest-id: true
  filesystem:
    settings-filename: ./prebid-server-settings.yaml
    stored-requests-dir: ./stored
    stored-imps-dir: ./stored
    stored-responses-dir: ./stored
    categories-dir:
gdpr:
  default-value: 1
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
