status-response: "ok"
adapters:
  generic:
    enabled: true
    endpoint: http://localhost:8091/generic-exchange
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: false
  generate-storedrequest-bidrequest-id: true
  filesystem:
    settings-filename: sample/configs/sample-app-settings-id5.yaml
    stored-requests-dir: sample/stored
    stored-imps-dir: sample/stored
    profiles-dir: sample/profiles
    stored-responses-dir: sample/stored
    categories-dir:
gdpr:
  default-value: 1
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
    v3:
      cache-dir: /var/tmp/vendor3
hooks:
  id5-user-id:
    enabled: true
    partner: 173
    fetchEndpoint: http://localhost:8091/id5-fetch
    inserterName: local-pbs.example.com
    providerName: local-pbs

logging:
  level:
    org.prebid.server.hooks.modules.id5: DEBUG

admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
